//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtremityExam
    {
        public int ExtremityExamId { get; set; }
        public string General { get; set; }
        public string Cyanosis { get; set; }
        public string Clubbing { get; set; }
        public string RUEEdema { get; set; }
        public string LUEEdema { get; set; }
        public string RLEEdema { get; set; }
        public string LLEEdema { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
