//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabType
    {
        public LabType()
        {
            this.PatientLabs = new HashSet<PatientLab>();
        }
    
        public int LabTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PatientLab> PatientLabs { get; set; }
    }
}
