//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLabResult
    {
        public int PatientLabResultId { get; set; }
        public int PatientId { get; set; }
        public int LabValueTypeId { get; set; }
        public int PatientLabId { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string DateModified { get; set; }
    
        public virtual LabValueType LabValueType { get; set; }
        public virtual PatientLabResult PatientLabResults1 { get; set; }
        public virtual PatientLabResult PatientLabResult1 { get; set; }
        public virtual PatientLab PatientLab { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
