//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedication
    {
        public int PatientMedicationId { get; set; }
        public string MedicationList { get; set; }
        public int PatientId { get; set; }
        public int MedicationTypeId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual MedicationType MedicationType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
