//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalExam
    {
        public int PhysicalExamId { get; set; }
        public string Temperature { get; set; }
        public string HeartRate { get; set; }
        public string RespiratoryRate { get; set; }
        public string BloodPressure { get; set; }
        public string O2Saturation { get; set; }
        public string Updated { get; set; }
        public Nullable<System.DateTime> LastBM { get; set; }
        public string Void { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
