//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public Prescription()
        {
            this.PrescriptionMedicationSyringes = new HashSet<PrescriptionMedicationSyrinx>();
            this.Syringes = new HashSet<Syrinx>();
        }
    
        public int PrescriptionId { get; set; }
        public Nullable<System.DateTime> DateFilled { get; set; }
        public string Rx { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int PatientId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<PrescriptionMedicationSyrinx> PrescriptionMedicationSyringes { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Syrinx> Syringes { get; set; }
    }
}
