//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiologyResult
    {
        public RadiologyResult()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int RadiologyResultId { get; set; }
        public Nullable<int> MRI { get; set; }
        public Nullable<int> XRAY { get; set; }
        public Nullable<int> CT { get; set; }
        public Nullable<int> Other { get; set; }
        public string Results { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
