//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewOfSystem
    {
        public int ReviewOfSystemId { get; set; }
        public Nullable<int> Constipation { get; set; }
        public Nullable<int> Nausea { get; set; }
        public Nullable<int> UrinaryRetention { get; set; }
        public Nullable<int> Weakness { get; set; }
        public Nullable<int> Fatigue { get; set; }
        public string Other { get; set; }
        public Nullable<int> OthersNegative { get; set; }
        public Nullable<int> NewOnSetNumbnessNeurological { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
