//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public Nullable<int> Lab { get; set; }
        public Nullable<int> Radiology { get; set; }
        public string InterimProviderNotes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int PatientId { get; set; }
        public int PatientLabId { get; set; }
        public int RadiologyResultId { get; set; }
    
        public virtual PatientLab PatientLab { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual RadiologyResult RadiologyResult { get; set; }
        public virtual Review Reviews1 { get; set; }
        public virtual Review Review1 { get; set; }
    }
}
