//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Prescriptions = new HashSet<Prescription>();
            this.Providers = new HashSet<Provider>();
        }
    
        public int StatusId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
