//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrengthExam
    {
        public int StrengthExamId { get; set; }
        public string PlantarFlexionRight { get; set; }
        public string PlantarFlexionLeft { get; set; }
        public string DorsiflexionRight { get; set; }
        public string DorsiflexionLeft { get; set; }
        public string FingerAbdRight { get; set; }
        public string FingerAbdLeft { get; set; }
        public string WristExtRight { get; set; }
        public string WristExtLeft { get; set; }
        public string BicepsRight { get; set; }
        public string BicepsLeft { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
