//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterPainSupportiveCareModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syrinx
    {
        public Syrinx()
        {
            this.PrescriptionMedicationSyringes = new HashSet<PrescriptionMedicationSyrinx>();
        }
    
        public int SyringeId { get; set; }
        public int PrescriptionId { get; set; }
    
        public virtual ICollection<PrescriptionMedicationSyrinx> PrescriptionMedicationSyringes { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
